name: Build-and-Test-CLANG-Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
     - '*'

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
  
    - name: Update Ubuntu and install the latest Clang compiler.
      run: |
            sudo apt update && sudo apt upgrade
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 19

    - name: Configure CMake
      run: |
            cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-19 -DBENCH_TYPE=BENCHMARK -DGENERATE_ASSEMBLY=TRUE 

    - name: Build the Test
      run: |
            cmake --build ./Build --config=${{matrix.build_type}}

    - name: Print assembly file
      run: |
            echo "Contents of Assembly.cod:"
            cat Assembly/Assembly.cod

    - name: Install the Test
      run: |
            sudo cmake --install ./Build --config=${{matrix.build_type}}

    - name: Run the Test
      run: |
            sudo chmod +x /usr/local/bin/BenchmarkExe
            sudo /usr/local/bin/BenchmarkExe
      continue-on-error: true
