name: Build-and-Test-CLANG-MacOS

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - index_processor_test

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest clang compiler.
      run: |
            brew install llvm

    - name: Install Nasm.
      run: |
            brew install nasm

    - name: Update Vcpkg and install other dependencies.
      run: |
            git clone https://github.com/Microsoft/Vcpkg ./vcpkg
            cd ./vcpkg
            ./bootstrap-vcpkg.sh
            git stash
            git pull
            ./vcpkg update

    - name: Install Jsonifier
      run: |
            sudo git clone https://github.com/RealTimeChris/Jsonifier --branch=dev --depth=1
            cd ./Jsonifier
            sudo cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
            sudo cmake --build ./Build --config=Release
            sudo cmake --install ./Build

    - name: Configure CMake.
      run: |
            cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ -DBENCH_TYPE=STRING_COMPARISON -DVCPKG_DIR=/Users/runner/work/BenchmarkSuite/BenchmarkSuite/vcpkg -DCPU_FREQUENCY_MHZ="true" -DJSONIFIER_LIBRARY="true"

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: /usr/local/Tests/${{matrix.build_type}}
      run: |
           sudo chmod +x /usr/local/Tests/${{matrix.build_type}}/StringComparisonExe    
           sudo ./StringComparisonExe
      continue-on-error: true
      