name: CPU info.

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  get-cpu-info:
    runs-on: macos-latest
    steps:
    - name: Get CPU Information
      run: sysctl -n machdep.cpu.brand_string
