name: Build-and-Test-GCC-Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - NewStrToD

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
  
    - name: Install the latest gcc compiler.
      run:  |
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install build-essential
            sudo apt-get install g++-12

    - name: Update Vcpkg and install other dependencies.
      run: | 
            sudo apt-get install nasm
            cd /usr/local/share/vcpkg
            ./bootstrap-vcpkg.sh
            git stash
            git pull
            vcpkg update

    - name: Install Jsonifier
      run: |
            sudo git clone https://github.com/RealTimeChris/Jsonifier --branch=dev --depth=1
            cd ./Jsonifier
            sudo cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
            sudo cmake --build ./Build --config=Release
            sudo cmake --install ./Build

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/g++-12 -DBENCH_TYPE=STRING_COMPARISON -DVCPKG_DIR=/usr/local/share/vcpkg -DJSONIFIER_LIBRARY="true" 

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: /usr/local/Tests/${{matrix.build_type}}
      run: |
           sudo chmod +x /usr/local/Tests/${{matrix.build_type}}/StringComparisonExe
           dir
           sudo ./StringComparisonExe
      continue-on-error: true